export const GOOGLE_PLACE_CUISINE_TYPE_MAP: Record<string, string> = {
  afghani_restaurant: 'afghani',
  african_restaurant: 'african',
  american_restaurant: 'american',
  asian_restaurant: 'asian',
  brazilian_restaurant: 'brazilian',
  chinese_restaurant: 'chinese',
  french_restaurant: 'french',
  greek_restaurant: 'greek',
  indian_restaurant: 'indian',
  indonesian_restaurant: 'indonesian',
  italian_restaurant: 'italian',
  japanese_restaurant: 'japanese',
  korean_restaurant: 'korean',
  lebanese_restaurant: 'lebanese',
  mediterranean_restaurant: 'mediterranean',
  mexican_restaurant: 'mexican',
  middle_eastern_restaurant: 'middle eastern',
  spanish_restaurant: 'spanish',
  thai_restaurant: 'thai',
  turkish_restaurant: 'turkish',
  vietnamese_restaurant: 'vietnamese',
};

export const GOOGLE_PLACE_NON_CUISINE_TYPE_MAP: Record<string, string> = {
  acai_shop: 'acai shop',
  bagel_shop: 'bagel shop',
  bakery: 'bakery',
  bar: 'bar',
  bar_and_grill: 'bar and grill',
  barbecue_restaurant: 'barbecue',
  breakfast_restaurant: 'breakfast restaurant',
  brunch_restaurant: 'brunch restaurant',
  buffet_restaurant: 'buffet',
  cafe: 'cafe',
  cafeteria: 'cafeteria',
  candy_store: 'candy store',
  cat_cafe: 'cat cafe',
  chocolate_factory: 'chocolate factory',
  chocolate_shop: 'chocolate shop',
  coffee_shop: 'coffee shop',
  confectionery: 'confectionery',
  deli: 'deli',
  dessert_restaurant: 'dessert restaurant',
  dessert_shop: 'dessert shop',
  diner: 'diner',
  dog_cafe: 'dog cafe',
  donut_shop: 'donut shop',
  fast_food_restaurant: 'fast food',
  fine_dining_restaurant: 'fine dining',
  food_court: 'food court',
  hamburger_restaurant: 'burger',
  ice_cream_shop: 'ice cream shop',
  juice_shop: 'juice shop',
  meal_delivery: 'delivery',
  meal_takeaway: 'takeout',
  pizza_restaurant: 'pizza',
  pub: 'pub',
  ramen_restaurant: 'ramen',
  sandwich_shop: 'sandwich shop',
  seafood_restaurant: 'seafood',
  steak_house: 'steakhouse',
  sushi_restaurant: 'sushi',
  tea_house: 'tea house',
  vegan_restaurant: 'vegan',
  vegetarian_restaurant: 'serves vegetarian food',
  wine_bar: 'wine bar',
};

export const GOOGLE_PLACE_TYPE_ATTRIBUTE_MAP: Record<string, string> = {
  ...GOOGLE_PLACE_CUISINE_TYPE_MAP,
  ...GOOGLE_PLACE_NON_CUISINE_TYPE_MAP,
};

export const GOOGLE_PLACE_TYPE_ATTRIBUTE_CANONICAL_NAMES = Array.from(
  new Set(
    Object.values(GOOGLE_PLACE_TYPE_ATTRIBUTE_MAP).filter(
      (value) => typeof value === 'string' && value.trim().length > 0,
    ),
  ),
);
