const CONTROL_HEIGHT = 30;
const CONTROL_RADIUS = 8; // fixed pill rounding
const CONTROL_HORIZONTAL_PADDING = 7;
const CONTROL_VERTICAL_PADDING = 5;

export { CONTROL_HEIGHT, CONTROL_RADIUS, CONTROL_HORIZONTAL_PADDING, CONTROL_VERTICAL_PADDING };
