server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker-logs
          __path__: /var/lib/docker/containers/*/*.log
          app: crave-search-api
    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            level: level
            message: message
            timestamp: timestamp
            service: service
            context: context
            operation: operation
            correlationId: correlationId
            environment: environment
            subreddit: subreddit
      - labels:
          level:
          context:
          operation:
          subreddit:
          service:
          correlationId:
          environment:
      - timestamp:
          source: timestamp
          format: RFC3339Nano
          location: UTC
