export type {
  Coordinate,
  DishPlaceData,
  DishPlaceData as DishRestaurantData,
  DishPlaceLocation,
  DishPlaceLocation as DishRestaurantLocation,
  DishResult,
  EntityScope,
  FilterClause,
  ItemResult,
  ItemResult as FoodResult,
  MapBounds,
  NaturalSearchRequest,
  OperatingStatus,
  Pagination,
  QueryEntity,
  QueryFormat,
  QueryPlan,
  PlaceItemSnippet,
  PlaceItemSnippet as RestaurantFoodSnippet,
  PlaceMatchedTag,
  PlaceMatchedTag as RestaurantMatchedTag,
  PlaceProfile,
  PlaceProfile as RestaurantProfile,
  PlaceResult,
  PlaceResult as RestaurantResult,
  PlaceResultScorePreview,
  PlaceResultScorePreview as RestaurantResultScorePreview,
  PlaceStatusPreview,
  PlaceStatusPreview as RestaurantStatusPreview,
  ScoreInfoSummary,
  SearchResponse,
  SearchResponseMetadata,
} from '@crave-search/shared';
