import type {
  SearchRootSuggestionInputPublicationArgsRuntime,
  UseSearchRootChromeInputPublicationArgsRuntimeArgs,
} from './use-search-root-chrome-input-publication-args-runtime-contract';

export const useSearchRootSuggestionInputPublicationArgsRuntime = ({
  rootSuggestionRuntime,
  rootScaffoldRuntime,
  sessionActionRuntime,
}: UseSearchRootChromeInputPublicationArgsRuntimeArgs): SearchRootSuggestionInputPublicationArgsRuntime => {
  const {
    shouldDriveSuggestionLayout,
    shouldShowSuggestionBackground,
    shouldShowSuggestionSurface,
    shouldRenderSuggestionPanel,
    shouldRenderAutocompleteSection,
    shouldRenderRecentSection,
    suggestionDisplaySuggestions,
    recentSearchesDisplay,
    recentlyViewedRestaurantsDisplay,
    recentlyViewedFoodsDisplay,
    hasRecentSearchesDisplay,
    hasRecentlyViewedRestaurantsDisplay,
    hasRecentlyViewedFoodsDisplay,
    isRecentLoadingDisplay,
    isRecentlyViewedLoadingDisplay,
    isRecentlyViewedFoodsLoadingDisplay,
    handleSuggestionContentSizeChange,
    suggestionHeaderHeightAnimatedStyle,
    suggestionScrollTopAnimatedStyle,
    suggestionScrollMaxHeightAnimatedStyle,
    suggestionHeaderDividerAnimatedStyle,
    suggestionScrollHandler,
    resolvedSuggestionHeaderHoles,
    suggestionTopFillHeight,
    suggestionScrollMaxHeightTarget,
    isSuggestionScreenActive,
    searchLayout,
  } = rootSuggestionRuntime;
  const {
    overlaySessionRuntime: { bottomInset },
  } = rootScaffoldRuntime;
  const { suggestionInteractionRuntime, foregroundInteractionRuntime } = sessionActionRuntime;

  return {
    suggestionInputsArgs: {
      shouldDisableSearchBlur: false,
      shouldShowSuggestionSurface,
      resolvedSuggestionHeaderHoles,
      suggestionHeaderHeightAnimatedStyle,
      shouldDriveSuggestionLayout,
      shouldShowSuggestionBackground,
      suggestionTopFillHeight,
      suggestionScrollTopAnimatedStyle,
      suggestionScrollMaxHeightTarget,
      suggestionScrollMaxHeightAnimatedStyle,
      searchLayoutTop: searchLayout.top,
      searchLayoutHeight: searchLayout.height,
      bottomInset,
      onSuggestionScroll: suggestionScrollHandler,
      onSuggestionContentSizeChange: handleSuggestionContentSizeChange,
      isSuggestionScreenActive,
      shouldRenderSuggestionPanel,
      shouldRenderAutocompleteSection,
      shouldRenderRecentSection,
      suggestionDisplaySuggestions,
      recentSearchesDisplay,
      recentlyViewedRestaurantsDisplay,
      recentlyViewedFoodsDisplay,
      hasRecentSearchesDisplay,
      hasRecentlyViewedRestaurantsDisplay,
      hasRecentlyViewedFoodsDisplay,
      isRecentLoadingDisplay,
      isRecentlyViewedLoadingDisplay,
      isRecentlyViewedFoodsLoadingDisplay,
      suggestionHeaderDividerAnimatedStyle,
      onSuggestionTouchStart: suggestionInteractionRuntime.handleSuggestionTouchStart,
      onSuggestionInteractionStart: suggestionInteractionRuntime.handleSuggestionInteractionStart,
      onSuggestionInteractionEnd: suggestionInteractionRuntime.handleSuggestionInteractionEnd,
      onSuggestionPress: foregroundInteractionRuntime.handleSuggestionPress,
      onRecentSearchPress: foregroundInteractionRuntime.handleRecentSearchPress,
      onRecentlyViewedRestaurantPress:
        foregroundInteractionRuntime.handleRecentlyViewedRestaurantPress,
      onRecentlyViewedFoodPress: foregroundInteractionRuntime.handleRecentlyViewedFoodPress,
      onRecentViewMorePress: foregroundInteractionRuntime.handleRecentViewMorePress,
      onRecentlyViewedMorePress: foregroundInteractionRuntime.handleRecentlyViewedMorePress,
    },
  };
};
