// GENERATED by scripts/search-harness/linker-calibration-sweep.ts — do not hand-edit.
// AUDIT H4 (2026-08-08, hand-annotated pending re-sweep): prefix/name/contains
// carried exactly the sweep's default pair (0.82/0.65) — unmeasured defaults
// laundered as measurements. Removed: they now fall through to
// LINKER_FALLBACK_FLOORS (the SAME pair), so behavior is identical and the
// artifact is honest about which tiers were actually observed. The sweep now
// omits under-observed tiers by construction.
// Provenance: 2026-07-05T21:39:44.885Z, corpus=974 single-edit perturbation pairs
// (+300 negative controls), decision-region observations=749,
// target precision=0.95. Margin fixed at 1.3 this pass (not swept).
// Regenerate after corpus refreshes or lattice/tier changes:
//   yarn ts-node scripts/search-harness/linker-calibration-sweep.ts

export interface LinkerTierFloors {
  /** Link outright at/above this similarity for this evidence tier. */
  absolute: number;
  /** Uncontested-singleton floor (no runner-up = infinite margin, higher bar). */
  singleton: number;
}

export const LINKER_TIER_FLOORS: Record<string, LinkerTierFloors> = {
  alias: {
    absolute: 0.95,
    singleton: 0.95,
  },
  fuzzy: {
    absolute: 0.67,
    singleton: 0.51,
  },
  edit: {
    absolute: 0.95,
    singleton: 0.65,
  },
};

export const LINKER_MARGIN = 1.3;
export const LINKER_MIN_FLOOR = 0.5;
