// GENERATED by scripts/search-harness/linker-calibration-sweep.ts — do not hand-edit.
// Provenance: 2026-07-05T21:39:44.885Z, corpus=974 single-edit perturbation pairs
// (+300 negative controls), decision-region observations=749,
// target precision=0.95. Margin fixed at 1.3 this pass (not swept).
// Regenerate after corpus refreshes or lattice/tier changes:
//   yarn ts-node scripts/search-harness/linker-calibration-sweep.ts

export interface LinkerTierFloors {
  /** Link outright at/above this similarity for this evidence tier. */
  absolute: number;
  /** Uncontested-singleton floor (no runner-up = infinite margin, higher bar). */
  singleton: number;
}

export const LINKER_TIER_FLOORS: Record<string, LinkerTierFloors> = {
  prefix: {
    absolute: 0.82,
    singleton: 0.65,
  },
  name: {
    absolute: 0.82,
    singleton: 0.65,
  },
  alias: {
    absolute: 0.95,
    singleton: 0.95,
  },
  fuzzy: {
    absolute: 0.67,
    singleton: 0.51,
  },
  contains: {
    absolute: 0.82,
    singleton: 0.65,
  },
  edit: {
    absolute: 0.95,
    singleton: 0.65,
  },
};

export const LINKER_MARGIN = 1.3;
export const LINKER_MIN_FLOOR = 0.5;
