import { StyleSheet } from 'react-native';

import { FONT_SIZES, LINE_HEIGHTS } from '../../constants/typography';
import { colors as themeColors } from '../../constants/theme';
import {
  OVERLAY_CORNER_RADIUS,
  OVERLAY_HORIZONTAL_PADDING,
} from '../../overlays/overlaySheetStyles';
import {
  ACTIVE_TAB_COLOR,
  CARD_LINE_GAP,
  CARD_VERTICAL_PADDING,
  CARD_VERTICAL_PADDING_BALANCE,
  CONTENT_HORIZONTAL_PADDING,
  FIRST_RESULT_TOP_PADDING_EXTRA,
  MARKER_SHADOW_STYLE,
  NAV_TOP_PADDING,
  PIN_BASE_HEIGHT,
  PIN_BASE_SCALE,
  PIN_BASE_WIDTH,
  PIN_FILL_LEFT_OFFSET,
  PIN_FILL_RENDER_HEIGHT,
  PIN_FILL_RENDER_WIDTH,
  PIN_FILL_TOP_OFFSET,
  PIN_MARKER_RENDER_SIZE,
  PIN_RANK_CONTAINER_HEIGHT,
  PIN_RANK_CONTAINER_WIDTH,
  PIN_RANK_FONT_SIZE,
  PIN_RANK_LEFT,
  PIN_RANK_TOP,
  PRICE_SLIDER_WRAPPER_HORIZONTAL_PADDING,
  PRICE_THUMB_SIZE,
  SEARCH_CONTAINER_PADDING_TOP,
  SEARCH_HORIZONTAL_PADDING,
  SEARCH_SHORTCUTS_BOTTOM_MARGIN,
  SEARCH_THIS_AREA_COLOR,
  RANK_BADGE_WIDTH,
  RESULT_DETAILS_INDENT,
  RESULT_TITLE_RIGHT_PADDING,
  SPACING_SM,
  SPACING_XS,
} from './constants/search';
import {
  CONTROL_HEIGHT,
  CONTROL_HORIZONTAL_PADDING,
  CONTROL_RADIUS,
  CONTROL_VERTICAL_PADDING,
} from './constants/ui';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  map: StyleSheet.absoluteFillObject,
  mapPlaceholder: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: themeColors.surface,
  },
  mapLoadingGrid: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: themeColors.background,
    zIndex: 2,
  },
  mapLoadingGridSvg: {
    ...StyleSheet.absoluteFillObject,
  },
  statusBarFade: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 5,
  },
  statusBarFadeLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  markerView: {
    flex: 0,
    alignSelf: 'flex-start',
  },
  userLocationMarkerView: {
    zIndex: 10000,
    elevation: 10000,
  },
  pinWrapper: {
    width: PIN_MARKER_RENDER_SIZE,
    height: PIN_MARKER_RENDER_SIZE,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  pinShadow: {
    ...MARKER_SHADOW_STYLE,
  },
  pinBase: {
    position: 'absolute',
    width: PIN_BASE_WIDTH * PIN_BASE_SCALE,
    height: PIN_BASE_HEIGHT * PIN_BASE_SCALE,
    resizeMode: 'contain',
  },
  pinFill: {
    position: 'absolute',
    width: PIN_FILL_RENDER_WIDTH,
    height: PIN_FILL_RENDER_HEIGHT,
    resizeMode: 'contain',
    left: PIN_FILL_LEFT_OFFSET,
    top: PIN_FILL_TOP_OFFSET,
  },
  pinRankWrapper: {
    // Container exactly matches pin fill bounds, centered on pin fill
    position: 'absolute',
    left: PIN_RANK_LEFT,
    top: PIN_RANK_TOP,
    width: PIN_RANK_CONTAINER_WIDTH,
    height: PIN_RANK_CONTAINER_HEIGHT,
    // Flexbox centering as primary method
    alignItems: 'center',
    justifyContent: 'center',
  },
  pinRank: {
    // Multiple centering methods for cross-platform reliability
    fontSize: PIN_RANK_FONT_SIZE,
    fontWeight: '700',
    color: '#fff',
    textAlign: 'center', // Horizontal centering
    textAlignVertical: 'center', // Android vertical centering
    lineHeight: PIN_RANK_CONTAINER_HEIGHT, // iOS vertical centering fallback
    includeFontPadding: false, // Remove Android extra padding
  },
  overlay: {
    flex: 1,
    justifyContent: 'flex-start',
    paddingBottom: 24,
    zIndex: 10,
  },
  searchChromeHidden: {
    opacity: 0,
  },
  searchContainer: {
    paddingHorizontal: SEARCH_HORIZONTAL_PADDING,
    paddingTop: SEARCH_CONTAINER_PADDING_TOP,
    zIndex: 50,
  },
  searchShortcutsRow: {
    paddingHorizontal: SEARCH_HORIZONTAL_PADDING,
    paddingTop: 2,
    marginBottom: SEARCH_SHORTCUTS_BOTTOM_MARGIN,
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 8,
    zIndex: 55,
  },
  searchShortcutChip: {
    borderRadius: 12,
    borderWidth: 0,
    backgroundColor: '#ffffff',
    paddingHorizontal: 11,
    paddingVertical: 8,
    justifyContent: 'center',
    alignSelf: 'flex-start',
    marginRight: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1.5 },
    shadowOpacity: 0.24,
    shadowRadius: 2,
    elevation: 2,
  },
  searchShortcutContent: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 6,
  },
  searchThisAreaContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    alignItems: 'center',
    zIndex: 30,
  },
  searchThisAreaButton: {
    height: CONTROL_HEIGHT + 4,
    borderRadius: CONTROL_RADIUS,
    borderWidth: 0,
    backgroundColor: '#ffffff',
    paddingHorizontal: CONTROL_HORIZONTAL_PADDING + 8,
    paddingVertical: CONTROL_VERTICAL_PADDING,
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1.5 },
    shadowOpacity: 0.24,
    shadowRadius: 2,
    elevation: 2,
  },
  searchThisAreaText: {
    color: SEARCH_THIS_AREA_COLOR,
  },
  searchShortcutChipText: {
    color: '#0f172a',
  },
  promptCardTopShadow: {
    borderRadius: 0,
  },
  promptCardWrapper: {
    borderRadius: 0,
  },
  promptCard: {
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    minHeight: 52,
  },
  promptRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 40,
  },
  promptInner: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 4,
    paddingVertical: 2,
    gap: 8,
  },
  searchBarTint: {
    backgroundColor: 'transparent',
  },
  searchSurface: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderColor: 'transparent',
    overflow: 'hidden',
    zIndex: 10,
  },
  searchSurfaceSolidBackground: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#ffffff',
  },
  searchSurfaceScroll: {
    alignSelf: 'stretch',
    width: '100%',
  },
  searchSuggestionHeaderSurface: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
  },
  searchSuggestionScrollSurface: {
    backgroundColor: 'transparent',
  },
  searchSuggestionScrollContent: {
    position: 'relative',
  },
  searchSuggestionScrollBackground: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#ffffff',
  },
  searchSuggestionTopFill: {
    position: 'absolute',
    left: 0,
    right: 0,
    backgroundColor: '#ffffff',
  },
  searchSurfaceContent: {
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  autocompleteSectionSurface: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    borderWidth: 1,
    borderColor: 'rgba(241, 245, 249, 0.8)',
  },
  recentSectionSurface: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    borderWidth: 1,
    borderColor: 'rgba(241, 245, 249, 0.8)',
  },
  autocompleteLoadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  autocompleteLoadingText: {
    fontSize: FONT_SIZES.body,
    lineHeight: LINE_HEIGHTS.body,
    color: themeColors.textBody,
    marginLeft: 8,
  },
  autocompleteEmptyText: {
    paddingHorizontal: 0,
    paddingVertical: 10,
    fontSize: FONT_SIZES.body,
    lineHeight: LINE_HEIGHTS.body,
    color: themeColors.textBody,
  },
  autocompleteItem: {
    paddingHorizontal: 0,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  autocompleteItemLast: {
    borderBottomWidth: 0,
  },
  autocompletePrimaryText: {
    fontSize: FONT_SIZES.subtitle,
    lineHeight: LINE_HEIGHTS.subtitle,
    fontWeight: '600',
    color: '#111827',
  },
  autocompleteSecondaryText: {
    fontSize: FONT_SIZES.body,
    lineHeight: LINE_HEIGHTS.body,
    color: themeColors.textBody,
    textTransform: 'capitalize',
  },
  recentHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  recentHeaderText: {
    fontSize: FONT_SIZES.body,
    lineHeight: LINE_HEIGHTS.body,
    fontWeight: '600',
    color: '#0f172a',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  recentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  },
  recentRowFirst: {
    borderTopWidth: 0,
  },
  recentIcon: {
    marginRight: 10,
  },
  recentText: {
    fontSize: FONT_SIZES.body,
    lineHeight: LINE_HEIGHTS.body,
    color: themeColors.textPrimary,
    flex: 1,
  },
  searchIcon: {
    marginRight: 12,
  },
  promptInput: {
    flex: 1,
    fontSize: FONT_SIZES.subtitle,
    lineHeight: LINE_HEIGHTS.subtitle,
    color: themeColors.textPrimary,
    textAlign: 'left',
    paddingVertical: 0,
    height: '100%',
  },
  trailingContainer: {
    marginLeft: 'auto',
    minWidth: 24,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  trailingButton: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  trailingPlaceholder: {
    width: 24,
    height: 24,
  },
  bottomNavWrapper: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    alignItems: 'stretch',
    zIndex: 120,
  },
  bottomNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 22,
    paddingTop: NAV_TOP_PADDING,
    backgroundColor: 'transparent',
    overflow: 'hidden',
  },
  bottomNavBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  navButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 68,
    paddingHorizontal: 4,
  },
  navIcon: {
    marginBottom: 2,
  },
  navLabel: {
    marginTop: 0,
    color: themeColors.textBody,
  },
  navLabelActive: {
    color: ACTIVE_TAB_COLOR,
  },
  scoreInfoIconButton: {
    padding: 0,
  },
  scoreInfoOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 130,
    justifyContent: 'flex-end',
  },
  scoreInfoBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.2)',
  },
  scoreInfoSheet: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: OVERLAY_CORNER_RADIUS,
    borderTopRightRadius: OVERLAY_CORNER_RADIUS,
    paddingHorizontal: CONTENT_HORIZONTAL_PADDING,
    paddingTop: 12,
  },
  scoreInfoGrabHandleWrapper: {
    alignItems: 'center',
    marginBottom: 6,
  },
  scoreInfoGrabHandle: {
    width: 42,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#e2e8f0',
  },
  scoreInfoContent: {
    gap: 12,
  },
  scoreInfoHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  scoreInfoTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  scoreInfoTitle: {
    color: '#0f172a',
  },
  scoreInfoValue: {
    color: themeColors.textPrimary,
  },
  scoreInfoClose: {
    padding: 6,
    borderRadius: 999,
  },
  scoreInfoSubtitle: {
    color: themeColors.textBody,
  },
  scoreInfoMetricsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  scoreInfoMetricItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#f8fafc',
  },
  scoreInfoMetricText: {
    color: '#0f172a',
  },
  scoreInfoMetricLabel: {
    color: themeColors.textBody,
  },
  scoreInfoDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: '#e2e8f0',
    marginVertical: 4,
  },
  scoreInfoDescription: {
    color: themeColors.textBody,
    lineHeight: LINE_HEIGHTS.body,
  },
  pollsIcon: {
    transform: [{ rotate: '90deg' }, { scaleX: -1 }],
  },
  resultsShadow: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderTopLeftRadius: OVERLAY_CORNER_RADIUS,
    borderTopRightRadius: OVERLAY_CORNER_RADIUS,
    backgroundColor: 'transparent',
  },
  resultsSheetSurface: {
    backgroundColor: 'transparent',
  },
  resultsListBackground: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#ffffff',
  },
  resultsListBackgroundLoading: {
    backgroundColor: '#ffffff',
  },
  resultsLoadingOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 52,
    backgroundColor: '#ffffff',
    zIndex: 2,
    elevation: 2,
  },
  resultsLoadingOverlayBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#ffffff',
    opacity: 1,
  },
  resultsLoadingOverlaySpinner: {
    paddingTop: 0,
  },
  resultsWashOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#ffffff',
  },
  resultsHeaderSurface: {
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: 'transparent',
    paddingHorizontal: CONTENT_HORIZONTAL_PADDING,
  },
  resultsHeaderSurfaceSolid: {
    backgroundColor: '#ffffff',
  },
  resultsHeaderHandle: {
    backgroundColor: 'transparent',
  },
  resultsCard: {
    flex: 1,
    borderTopLeftRadius: OVERLAY_CORNER_RADIUS,
    borderTopRightRadius: OVERLAY_CORNER_RADIUS,
    paddingVertical: 0,
    paddingHorizontal: 0,
    backgroundColor: 'transparent',
    alignSelf: 'stretch',
  },
  resultsCardSurface: {
    backgroundColor: '#ffffff',
  },
  resultsCardCentered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 48,
  },
  resultsScroll: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  resultsListHeader: {
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: 'transparent',
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  resultsEmptyArea: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 0,
    backgroundColor: '#ffffff',
  },
  onDemandNotice: {
    alignSelf: 'stretch',
    marginHorizontal: CONTENT_HORIZONTAL_PADDING,
    marginBottom: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: themeColors.border,
    backgroundColor: themeColors.background,
  },
  onDemandNoticeText: {
    color: themeColors.textBody,
    textAlign: 'center',
  },
  submittedQueryLabel: {
    flexShrink: 1,
    marginRight: 12,
    color: '#0f172a',
    marginBottom: 0,
    paddingLeft: 0,
  },
  resultsInner: {
    width: '100%',
  },
  loadMoreSpacer: {
    minHeight: 120,
    alignItems: 'stretch',
    justifyContent: 'center',
    paddingBottom: 20,
  },
  loadMoreSpinner: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 8,
  },
  resultFiltersWrapper: {
    marginTop: -3,
    marginBottom: 14,
    gap: 0,
  },
  priceSheetOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  priceSheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.2)',
  },
  priceSheetContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    borderTopLeftRadius: OVERLAY_CORNER_RADIUS,
    borderTopRightRadius: OVERLAY_CORNER_RADIUS,
    backgroundColor: '#ffffff',
    paddingHorizontal: OVERLAY_HORIZONTAL_PADDING,
    paddingTop: 12,
  },
  priceSheetHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 10,
  },
  priceSheetHeadline: {
    flex: 1,
    minWidth: 0,
    color: '#0f172a',
  },
  priceSheetSliderWrapper: {
    width: '100%',
    paddingHorizontal: PRICE_SLIDER_WRAPPER_HORIZONTAL_PADDING,
    marginTop: 0,
    marginBottom: 8,
  },
  priceTrackContainer: {
    width: '100%',
    height: 32,
    justifyContent: 'center',
  },
  priceSliderRail: {
    position: 'absolute',
    left: PRICE_THUMB_SIZE / 2,
    right: PRICE_THUMB_SIZE / 2,
    height: 3,
    borderRadius: 999,
    backgroundColor: `${themeColors.primary}17`,
    top: '50%',
    marginTop: -1.5,
  },
  priceSliderRailSelected: {
    position: 'absolute',
    height: 3,
    borderRadius: 999,
    backgroundColor: themeColors.primary,
    top: '50%',
    marginTop: -1.5,
  },
  priceSliderThumb: {
    position: 'absolute',
    top: 6,
    width: PRICE_THUMB_SIZE,
    height: PRICE_THUMB_SIZE,
    borderRadius: PRICE_THUMB_SIZE / 2,
    backgroundColor: themeColors.primary,
  },
  priceSheetDoneButton: {
    height: CONTROL_HEIGHT,
    borderRadius: CONTROL_RADIUS,
    paddingHorizontal: CONTROL_HORIZONTAL_PADDING + 4,
    paddingVertical: CONTROL_VERTICAL_PADDING,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-end',
  },
  priceSheetDoneText: {
    color: '#ffffff',
  },
  resultItem: {
    paddingTop: CARD_VERTICAL_PADDING - CARD_VERTICAL_PADDING_BALANCE,
    paddingBottom: CARD_VERTICAL_PADDING + CARD_VERTICAL_PADDING_BALANCE,
    paddingHorizontal: CONTENT_HORIZONTAL_PADDING,
    backgroundColor: '#ffffff',
    alignSelf: 'stretch',
    borderRadius: 0,
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  resultItemSeparator: {
    height: 1,
    width: '100%',
    backgroundColor: '#ffffff',
  },
  resultItemSeparatorLine: {
    height: 1,
    backgroundColor: '#f1f5f9',
    marginHorizontal: CONTENT_HORIZONTAL_PADDING,
  },
  firstResultItem: {
    paddingTop:
      CARD_VERTICAL_PADDING - CARD_VERTICAL_PADDING_BALANCE + FIRST_RESULT_TOP_PADDING_EXTRA,
  },
  resultItemWithFilters: {
    paddingTop: CARD_VERTICAL_PADDING - CARD_VERTICAL_PADDING_BALANCE,
  },
  resultPressable: {
    width: '100%',
  },
  resultHeader: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minHeight: 32,
    marginBottom: 0,
  },
  resultActions: {
    position: 'absolute',
    top: 0,
    right: -(CONTENT_HORIZONTAL_PADDING / 2),
    width: 32,
    flexDirection: 'column',
    alignItems: 'center',
    gap: 4,
  },
  resultTitleContainer: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'flex-start',
    minHeight: 0,
    paddingTop: 0,
    gap: CARD_LINE_GAP,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: CARD_LINE_GAP,
    maxWidth: '100%',
  },
  titleRowWithActions: {
    paddingRight: RESULT_TITLE_RIGHT_PADDING,
  },
  rankBadge: {
    width: RANK_BADGE_WIDTH,
    height: 30,
    borderRadius: 15,
    backgroundColor: themeColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rankBadgeText: {
    fontSize: FONT_SIZES.title,
    lineHeight: 30, // Match container height exactly for vertical centering
    color: '#ffffff',
    fontWeight: '700',
    textAlign: 'center',
    textAlignVertical: 'center',
    includeFontPadding: false,
  },
  cardBodyStack: {
    width: '100%',
    gap: CARD_LINE_GAP,
    paddingLeft: RESULT_DETAILS_INDENT,
  },
  coverageBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: themeColors.border,
    backgroundColor: '#eef2f6',
  },
  coverageBadgeText: {
    color: themeColors.textBody,
    letterSpacing: 0.2,
  },
  resultMetaLine: {
    marginTop: 0,
  },
  dishMetaLineFirst: {
    marginTop: 0,
  },
  metricBlock: {
    marginTop: 0,
    marginBottom: 0,
    gap: CARD_LINE_GAP,
  },
  metricLine: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    columnGap: 4,
    rowGap: 2,
  },
  metricIcon: {
    marginRight: 2,
  },
  restaurantScoreIcon: {
    marginRight: 1,
  },
  metricDot: {
    color: themeColors.textBody,
    fontSize: FONT_SIZES.body,
    lineHeight: LINE_HEIGHTS.body,
    marginHorizontal: SPACING_SM,
  },
  metricLabel: {
    color: themeColors.textBody,
    letterSpacing: 0.2,
    textTransform: 'none',
  },
  metricValueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  metricValue: {
    color: themeColors.textPrimary,
  },
  metricCountersInline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  metricCounterItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  metricCounterText: {
    color: themeColors.textBody,
  },
  metricSupportRow: {
    marginTop: 0,
  },
  restaurantMetricRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'nowrap',
    minWidth: 0,
    columnGap: SPACING_XS,
    rowGap: CARD_LINE_GAP,
  },
  restaurantMetricLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 1,
    minWidth: 0,
    columnGap: 4,
  },
  restaurantMetricLabel: {
    flexShrink: 1,
    minWidth: 0,
  },
  restaurantMetricRight: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 0,
    flexShrink: 1,
    minWidth: 0,
    columnGap: SPACING_XS,
  },
  metricSupportLabel: {
    color: themeColors.textBody,
    letterSpacing: 0.1,
  },
  resultMetaLineRight: {
    marginTop: 0,
    marginLeft: 'auto',
    alignItems: 'flex-end',
    maxWidth: '65%',
    flexShrink: 1,
  },
  resultMetaLineInline: {
    marginTop: 0,
    flexShrink: 1,
  },
  resultMetaText: {
    color: themeColors.textBody,
    flexShrink: 1,
    includeFontPadding: false,
    lineHeight: LINE_HEIGHTS.body,
  },
  resultMetaPrefix: {
    color: themeColors.textBody,
  },
  resultMetaTextRight: {
    textAlign: 'right',
  },
  resultMetaOpen: {
    color: '#16a34a',
  },
  resultMetaClosingSoon: {
    color: '#f59e0b',
  },
  resultMetaSuffix: {
    color: themeColors.textBody,
  },
  resultMetaClosed: {
    color: '#dc2626',
  },
  resultMetaSeparator: {
    color: themeColors.textBody,
  },
  resultMetaPrice: {
    color: themeColors.textBody,
  },
  resultMetaDistance: {
    color: themeColors.textBody,
  },
  dishMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 8,
    marginTop: 0,
  },
  userLocationWrapper: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
  },
  userLocationHaloWrapper: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    backgroundColor: 'rgba(255, 255, 255, 0.65)',
  },
  userLocationShadow: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    ...MARKER_SHADOW_STYLE,
  },
  userLocationDot: {
    width: 9,
    height: 9,
    borderRadius: 4.5,
    backgroundColor: themeColors.secondaryAccent,
  },
  userLocationHalo: {
    width: 34,
    height: 34,
    borderRadius: 17,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.65)',
  },
  shareButton: {
    padding: 4,
    borderRadius: 999,
  },
  likeButton: {
    padding: 4,
    borderRadius: 999,
  },
  resultContent: {
    marginLeft: 0,
    marginTop: 0,
    paddingBottom: 0,
    paddingLeft: RESULT_DETAILS_INDENT,
  },
  resultContentStack: {
    gap: CARD_LINE_GAP,
  },
  secondaryMetricsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 6,
  },
  secondaryMetricItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  secondaryMetricInline: {
    color: themeColors.textBody,
  },
  emptyState: {
    paddingVertical: 0,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  textSlate900: {
    color: themeColors.textPrimary,
  },
  textSlate700: {
    color: themeColors.textBody,
  },
  textSlate600: {
    color: themeColors.textBody,
  },
  textSlate500: {
    color: themeColors.textMuted,
  },
  textRed600: {
    color: '#dc2626',
  },
  dishTitle: {
    fontSize: FONT_SIZES.subtitle,
    lineHeight: LINE_HEIGHTS.subtitle,
    flexShrink: 1,
    minWidth: 0,
  },
  dishCardTitle: {
    flexShrink: 1,
    minWidth: 0,
  },
  dishRestaurantName: {
    color: themeColors.textMuted,
    flexShrink: 1,
    minWidth: 0,
  },
  dishSubtitle: {
    fontSize: FONT_SIZES.body,
    lineHeight: LINE_HEIGHTS.body,
    marginTop: 4,
  },
  dishSubtitleSmall: {
    fontSize: FONT_SIZES.caption,
    lineHeight: LINE_HEIGHTS.caption,
  },
  topFoodSection: {
    marginTop: 0,
    marginBottom: 0,
    gap: CARD_LINE_GAP,
  },
  topFoodLabel: {
    color: themeColors.textBody,
    letterSpacing: 0.6,
    textTransform: 'none',
  },
  topFoodLabelStrong: {
    color: themeColors.textBody,
  },
  topFoodHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING_SM,
  },
  topFoodAvgRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING_SM,
  },
  topFoodDivider: {
    flex: 1,
    height: 0,
    backgroundColor: 'transparent',
  },
  topFoodInlineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 0,
    minWidth: 0,
    width: '100%',
    columnGap: CARD_LINE_GAP,
    rowGap: CARD_LINE_GAP,
  },
  topFoodInlineList: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'nowrap',
    columnGap: CARD_LINE_GAP,
    flexShrink: 1,
    minWidth: 0,
  },
  topFoodInlineItem: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 6,
    minWidth: 0,
  },
  topFoodInlineText: {
    color: themeColors.textBody,
    flexShrink: 0,
    minWidth: 0,
  },
  topFoodRankInline: {
    color: themeColors.primary,
  },
  topFoodNameInline: {
    color: themeColors.textBody,
  },
  topFoodMore: {
    color: themeColors.secondaryAccent,
    marginTop: 0,
    alignSelf: 'flex-start',
    paddingLeft: 0,
    flexShrink: 0,
  },
  topFoodInlineMeasure: {
    position: 'absolute',
    opacity: 0,
    left: 0,
    top: 0,
    pointerEvents: 'none',
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'nowrap',
    columnGap: CARD_LINE_GAP,
    alignSelf: 'flex-start',
  },
  topFoodMeasureText: {
    color: themeColors.textBody,
  },
  resultContentStatusLine: {
    marginTop: 0,
    marginBottom: 0,
  },
  loadingText: {
    marginTop: 16,
    fontSize: FONT_SIZES.subtitle,
    lineHeight: LINE_HEIGHTS.subtitle,
    textAlign: 'center',
  },
  glassHighlightSmall: {
    position: 'absolute',
    width: 0,
    height: 0,
  },
});

export default styles;
